# name: Deployment

# on:
#   push:
#     branches: ["main"]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - run: docker build . -t hpsanjel/ourghareluachar
#       - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}}
#       - run: docker push harisanjel/ourghareluachar:latest
